### ISSUE TITLE
Enhance the Display of AI Section Data with Better Styling

### ISSUE THREAD

**Issue by TharunKumarrA** [TharunKumarrA/Molecule-Visualiser-DSA#6]
## Description
Currently, the data retrieved from Bard in the **AI Section** is being dumped as plain Markdown. This results in a basic and unappealing display. We need to enhance the presentation of this data to improve readability and user experience.

## Acceptance Criteria
- Data in the **AI Section** is displayed with improved styling and formatting.
- Maintain Markdown support for structured content (e.g., lists, headings, bold text).
- Add visual enhancements like:
  - Consistent fonts and colors.
  - Proper spacing and alignment.
  - Styling for lists, headings, and other Markdown elements.

## Suggested Approach
1. Use a **Markdown renderer** with custom styling to improve the appearance of the content.
2. Leverage Tailwind CSS (or the existing styling framework) to style the rendered Markdown elements.
3. Test the new design with sample Bard data to ensure correctness.

---

### File: `/src/components/AISection.jsx`
- **Update Logic:**
  - Replace the plain Markdown renderer with a styled Markdown renderer (e.g., ReactMarkdown with custom components).
  - Add styles for common Markdown elements (e.g., headings, lists, bold text).

### File: `/src/index.css`
- **Add Styling:**
  - Define CSS classes or Tailwind utilities for:
    - Headings
    - Lists
    - Paragraphs
    - Spacing and alignment

---

### In `AISection.jsx`
Replace the current plain Markdown renderer with enhanced styling:
```javascript
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm"; // Support for tables, task lists, etc.

export default function AiSection({ compoundFormula }) {
  const [res, setResponse] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleGetData = () => {
    setIsLoading(true);
    axios
      .get(`base-url/getinfo/${compoundFormula}`)
      .then((response) => {
        console.log(response.data);
        setResponse(response.data);
        setIsLoading(false);
      })
      .catch((error) => {
        console.error("Error fetching data:", error);
        setIsLoading(false);
      });
  };

  return (
    <div className="overflow-y-scroll p-4 no-scrollbar w-full">
      {isLoading ? (
        <p>Loading...</p>
      ) : (
        <>
          {!res && (
            <button
              onClick={handleGetData}
              className="flex justify-center items-center border-2 border-[#2ABD91] py-2 rounded-full mx-auto cursor-pointer px-6"
            >
              GET DATA
            </button>
          )}
          {res && (
            <ReactMarkdown
              className="prose prose-lg text-white"
              children={res}
              remarkPlugins={[remarkGfm]}
            />
          )}
        </>
      )}
    </div>
  );
}
```
### In `index.css`
Add styles for Markdown elements:
```css
.prose h1 {
  font-size: 1.875rem;
  font-weight: bold;
  color: #2ABD91;
}

.prose h2 {
  font-size: 1.5rem;
  font-weight: semi-bold;
  color: #87CEEB;
}

.prose p {
  font-size: 1rem;
  line-height: 1.5;
  color: #ffffff;
}

.prose ul {
  list-style-type: disc;
  padding-left: 1.5rem;
  color: #ffffff;
}

.prose li {
  margin-bottom: 0.5rem;
}
```
